Public Class Constants
    Public Shared ReadOnly IDENT_ACLIST_PUBLISHER As String = "autocompletelistpublisher"
    Public Shared ReadOnly IDENT_ACLIST_AUTHOR As String = "autocompletelistauthor"
    Public Shared ReadOnly IDENT_ACLIST_SHELF As String = "autocompletelistshelves"
    Public Shared ReadOnly IDENT_ACLIST_SERIES As String = "autocompletelistseriestitles"


    Public Shared ReadOnly IDENT_STAFF_ID As String = "staffid"
    Public Shared ReadOnly IDENT_STAFF_NAME As String = "staffname"
    Public Shared ReadOnly IDENT_STAFF_EMP_NUMBER As String = "staffemployeenumber"
    Public Shared ReadOnly IDENT_STAFF_ROLE As String = "staffrolefromthedatabse"

    Public Shared ReadOnly IDENT_USER_ID As String = "userid"
    Public Shared ReadOnly IDENT_BOOK_ID As String = "bookid"
    Public Shared ReadOnly IDENT_USER_NAME As String = "username"
    Public Shared ReadOnly IDENT_USER_NIC As String = "usernic"
    Public Shared ReadOnly IDENT_USER_MEMBER As String = "usermembernumber"
    Public Shared ReadOnly IDENT_USER_PAYREQ As String = "payreq"
    Public Shared ReadOnly IDENT_USER_PAY_SUCCESS_REDIRECT As String = "paysuccedredirectedpage"
    Public Shared ReadOnly IDENT_NEWPAY As String = "newusrjoin"
    Public Shared ReadOnly IDENT_PAYTYPE As String = "userpaymenttype"
    Public Shared ReadOnly IDENT_USER_LOGIN As String = "userisloggedin"

    Public Shared ReadOnly IDENT_SEARCH2LOGIN As String = "redirectsearchlogin"
    Public Shared ReadOnly IDENT_SEARCHTERM As String = "redirectusersearchterm"


    Public Shared ReadOnly IDENT_MODEL1 As String = "objectmodel1"
    Public Shared ReadOnly IDENT_MODEL2 As String = "objectmodel2"

    Public Shared ReadOnly IDENT_SESS_EXP As String = "sessionexpiry"
    Public Shared ReadOnly IDENT_ERR_ACCESS_DENIED As String = "accessdenied"
    Public Shared ReadOnly IDENT_REQ_FAIL_ONE As String = "fail1"
    Public Shared ReadOnly IDENT_REQ_FAIL_TWO As String = "fail2"
    Public Shared ReadOnly IDENT_REQ_FAIL_THREE As String = "fail3"
    Public Shared ReadOnly IDENT_REQ_FAIL_REASON As String = "failreason"
    Public Shared ReadOnly IDENT_REQ_SUCCESS As String = "success"
    Public Shared ReadOnly IDENT_USER_PAY_SUCCESS As String = "usrpaysuccess"
    Public Shared ReadOnly IDENT_USER_QR As String = "usridentqr"
    Public Shared ReadOnly IDENT_QUERY_ERROR As String = "qeuryexceptionstring"

    Public Shared ReadOnly IDENT_TEMPDATA_USERMODEL As String = "foundusermodelintempdata"


    Public Shared ReadOnly COUNTRY_LIST() As String = New String() {"Afghanistan",
                                                                    "Albania",
                                                                    "Algeria",
                                                                    "Andorra",
                                                                    "Angola",
                                                                    "Antigua and Barbuda",
                                                                    "Argentina",
                                                                    "Armenia",
                                                                    "Australia",
                                                                    "Austria",
                                                                    "Azerbaijan",
                                                                    "Bahamas",
                                                                    "Bahrain",
                                                                    "Bangladesh",
                                                                    "Barbados",
                                                                    "Belarus",
                                                                    "Belgium",
                                                                    "Belize",
                                                                    "Benin",
                                                                    "Bhutan",
                                                                    "Bolivia",
                                                                    "Bosnia and Herzegovina",
                                                                    "Botswana",
                                                                    "Brazil",
                                                                    "Brunei",
                                                                    "Bulgaria",
                                                                    "Burkina Faso",
                                                                    "Burundi",
                                                                    "Côte d'Ivoire",
                                                                    "Cabo Verde",
                                                                    "Cambodia",
                                                                    "Cameroon",
                                                                    "Canada",
                                                                    "Central African Republic",
                                                                    "Chad",
                                                                    "Chile",
                                                                    "China",
                                                                    "Colombia",
                                                                    "Comoros",
                                                                    "Congo (Congo-Brazzaville)",
                                                                    "Costa Rica",
                                                                    "Croatia",
                                                                    "Cuba",
                                                                    "Cyprus",
                                                                    "Czechia (Czech Republic)",
                                                                    "Democratic Republic of the Congo",
                                                                    "Denmark",
                                                                    "Djibouti",
                                                                    "Dominica",
                                                                    "Dominican Republic",
                                                                    "Ecuador",
                                                                    "Egypt",
                                                                    "El Salvador",
                                                                    "Equatorial Guinea",
                                                                    "Eritrea",
                                                                    "Estonia",
                                                                    "Eswatini",
                                                                    "Swaziland",
                                                                    "Ethiopia",
                                                                    "Fiji",
                                                                    "Finland",
                                                                    "France",
                                                                    "Gabon",
                                                                    "Gambia",
                                                                    "Georgia",
                                                                    "Germany",
                                                                    "Ghana",
                                                                    "Greece",
                                                                    "Grenada",
                                                                    "Guatemala",
                                                                    "Guinea",
                                                                    "Guinea-Bissau",
                                                                    "Guyana",
                                                                    "Haiti",
                                                                    "Holy See",
                                                                    "Honduras",
                                                                    "Hungary",
                                                                    "Iceland",
                                                                    "India",
                                                                    "Indonesia",
                                                                    "Iran",
                                                                    "Iraq",
                                                                    "Ireland",
                                                                    "Israel",
                                                                    "Italy",
                                                                    "Jamaica",
                                                                    "Japan",
                                                                    "Jordan",
                                                                    "Kazakhstan",
                                                                    "Kenya",
                                                                    "Kiribati",
                                                                    "Kuwait",
                                                                    "Kyrgyzstan",
                                                                    "Laos",
                                                                    "Latvia",
                                                                    "Lebanon",
                                                                    "Lesotho",
                                                                    "Liberia",
                                                                    "Libya",
                                                                    "Liechtenstein",
                                                                    "Lithuania",
                                                                    "Luxembourg",
                                                                    "Madagascar",
                                                                    "Malawi",
                                                                    "Malaysia",
                                                                    "Maldives",
                                                                    "Mali",
                                                                    "Malta",
                                                                    "Marshall Islands",
                                                                    "Mauritania",
                                                                    "Mauritius",
                                                                    "Mexico",
                                                                    "Micronesia",
                                                                    "Moldova",
                                                                    "Monaco",
                                                                    "Mongolia",
                                                                    "Montenegro",
                                                                    "Morocco",
                                                                    "Mozambique",
                                                                    "Myanmar (formerly Burma)",
                                                                    "Namibia",
                                                                    "Nauru",
                                                                    "Nepal",
                                                                    "Netherlands",
                                                                    "New Zealand",
                                                                    "Nicaragua",
                                                                    "Niger",
                                                                    "Nigeria",
                                                                    "North Korea",
                                                                    "North Macedonia",
                                                                    "Norway",
                                                                    "Oman",
                                                                    "Pakistan",
                                                                    "Palau",
                                                                    "Palestine State",
                                                                    "Panama",
                                                                    "Papua New Guinea",
                                                                    "Paraguay",
                                                                    "Peru",
                                                                    "Philippines",
                                                                    "Poland",
                                                                    "Portugal",
                                                                    "Qatar",
                                                                    "Romania",
                                                                    "Russia",
                                                                    "Rwanda",
                                                                    "Saint Kitts and Nevis",
                                                                    "Saint Lucia",
                                                                    "Saint Vincent and the Grenadines",
                                                                    "Samoa",
                                                                    "San Marino",
                                                                    "Sao Tome and Principe",
                                                                    "Saudi Arabia",
                                                                    "Senegal",
                                                                    "Serbia",
                                                                    "Seychelles",
                                                                    "Sierra Leone",
                                                                    "Singapore",
                                                                    "Slovakia",
                                                                    "Slovenia",
                                                                    "Solomon Islands",
                                                                    "Somalia",
                                                                    "South Africa",
                                                                    "South Korea",
                                                                    "South Sudan",
                                                                    "Spain",
                                                                    "Sri Lanka",
                                                                    "Sudan",
                                                                    "Suriname",
                                                                    "Sweden",
                                                                    "Switzerland",
                                                                    "Syria",
                                                                    "Tajikistan",
                                                                    "Tanzania",
                                                                    "Thailand",
                                                                    "Timor-Leste",
                                                                    "Togo",
                                                                    "Tonga",
                                                                    "Trinidad and Tobago",
                                                                    "Tunisia",
                                                                    "Turkey",
                                                                    "Turkmenistan",
                                                                    "Tuvalu",
                                                                    "Uganda",
                                                                    "Ukraine",
                                                                    "United Arab Emirates",
                                                                    "United Kingdom",
                                                                    "United States of America",
                                                                    "Uruguay",
                                                                    "Uzbekistan",
                                                                    "Vanuatu",
                                                                    "Venezuela",
                                                                    "Vietnam",
                                                                    "Yemen",
                                                                    "Zambia",
                                                                    "Zimbabwe"
                                                                    }
End Class
